FROM ghcr.io/webassembly/wasi-sdk:main

RUN DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -qy update && \
    DEBIAN_FRONTEND=noninteractive apt --no-install-recommends -qy install \
    binutils \
    build-essential \
    ca-certificates \
    file \
    git \
    docker.io \
    pkg-config \
    ninja-build \
    jq \
    autoconf \
    autoconf-archive \
    automake \
    zlib1g-dev \
    libxml2 \
    python3 \
    python3-pip \
    wget \
    curl \
    zip \
    unzip \
    git \
    git-lfs \
    ssh-client \
    build-essential \
    make \
    ant \
    libidn12 \
    cmake
